### ISSUE TITLE
Add upper bound to `errors` dependency

### ISSUE THREAD

**Issue by Gabriel439** [jcristovao/data-easy#1]
`errors-2.0` will be switching to use `ExceptT` instead of `EitherT`.  If that will break your package, then add an upper bound of `errors < 2.0` to your dependencies.

**Comment by jcristovao** [comment]
Hi,
I'm sorry for the late reply, and thanks for the patch. 
I will merge it and update hackage still today.

Also, the move to transformers except seems a good one, I'll probably do the same one of this days for all my packages.

Thanks!
